version: "3"
services:
  cms:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    volumes:
        - ./posts:/app/posts
        - ./public:/app/public
  api:
    build: ./api
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
        - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 # nginx:
 #    image: nginx:latest
 #    depends_on:
 #        - cms
 #        - www
 #    volumes:
 #        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
 #    ports:
 #        - 80:80
 #        - 443:443
