version: "3"
services:
  cms:
    build:
      context: ./
      dockerfile: Dockerfile.dev
  www:
    build:
      context: ./
      dockerfile: Dockerfile.prod
  nginx: 
    image: nginx:latest
    depends_on:
        - cms
        - www
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - 80:80
        - 443:443
